### ISSUE TITLE
HTML: Each chapter should be a separate page, with navigation in header and footer

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#5] opened 2019-12-27 13:12 UTC
HTML: Each chapter should be a separate page, with navigation in header and footer. Footer should also contain sharing links, without JavaScript, like sharing links below this article: 
[https://svedic.org/programming/thanks-economist-fix-the-internet](https://svedic.org/programming/thanks-economist-fix-the-internet)

**Comment by ZSvedic** [comment] 2020-01-15 16:03
Example: https://git-scm.com/book/en/v2/Appendix-C%3A-Git-Commands-Inspection-and-Comparison

**Comment by reinaldoarrosi** [comment] 2020-01-20 11:15
Pandoc does not support having multiple HTML files and linking between them. This would require a custom-written script that would post-process HTML files. Since this is a bit complex we decided to keep everything in a single HTML file and use a bit of javascript to show/hide chapters as the user navigates the book.

**Comment by reinaldoarrosi** [comment] 2020-01-21 18:11
Fixed by https://github.com/ZSvedic/EBH-book/commit/4da52f0ec6bdd6105a4ec24c1854336b16d9edeb

**Comment by ZSvedic** [comment] 2020-01-23 09:02
I can't build HTML on my machine, I get this error:
![image](https://user-images.githubusercontent.com/43754593/72970203-645faf00-3dc7-11ea-9a45-a90ea590ebe3.png)

**Comment by reinaldoarrosi** [comment] 2020-01-23 11:22
I wasn't able to reproduce it but, looking at the error message, I think I found what's wrong.
I've made a fix for it, please pull these changes try building again.

**Closed as completed by reinaldoarrosi** 2020-01-23 11:22 UTC
Labels: HTML

**Comment by ZSvedic** [comment] 2020-01-23 16:21
@reinaldoarrosi Yes, now it works.
